version: "3.8"

services:
  app_blue:
    image: ghcr.io/srarmstrong/mapabove:latest
    container_name: mapabove_blue
    restart: always
    ports:
      - "8081:80"    
  app_green:
    image: ghcr.io/srarmstrong/mapabove:latest
    container_name: mapabove_green
    restart: always
    ports:
      - "8082:80"    

  proxy:
    image: nginx:alpine
    container_name: mapabove_proxy
    restart: always
    depends_on:
      - app_blue
      - app_green
    ports:
      - "80:80"       
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
